[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "second_py_package"
dynamic = ["version"]

[tool.setuptools_scm]
write_to = "second_py_package/_version.py"