# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.1.3.dev0+gc050831.d20230404'
__version_tuple__ = version_tuple = (1, 1, 3, 'dev0', 'gc050831.d20230404')
