# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.1.1.dev0+gf7482ad.d20230404'
__version_tuple__ = version_tuple = (1, 1, 1, 'dev0', 'gf7482ad.d20230404')
